// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using imobiliariaCivitas_api.Data;

#nullable disable

namespace imobiliariaCivitas_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240825013305_CriacaoBanco")]
    partial class CriacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("imobiliariaCivitas_shared.tb_imagem", b =>
                {
                    b.Property<int>("cd_imagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cd_imagem"));

                    b.Property<int>("cd_imovel")
                        .HasColumnType("integer");

                    b.Property<string>("imageBase64")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<int?>("tb_imovelcd_imovel")
                        .HasColumnType("integer");

                    b.HasKey("cd_imagem");

                    b.HasIndex("tb_imovelcd_imovel");

                    b.ToTable("tb_imagem", (string)null);
                });

            modelBuilder.Entity("imobiliariaCivitas_shared.tb_imovel", b =>
                {
                    b.Property<int>("cd_imovel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cd_imovel"));

                    b.Property<DateTime>("criadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("descricao");

                    b.HasKey("cd_imovel");

                    b.ToTable("tb_imovel", (string)null);
                });

            modelBuilder.Entity("imobiliariaCivitas_shared.tb_imagem", b =>
                {
                    b.HasOne("imobiliariaCivitas_shared.tb_imovel", null)
                        .WithMany("imagens")
                        .HasForeignKey("tb_imovelcd_imovel");
                });

            modelBuilder.Entity("imobiliariaCivitas_shared.tb_imovel", b =>
                {
                    b.Navigation("imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
